### ISSUE TITLE
Grafana Sidecar Dashboards has to be enabled

### ISSUE THREAD

**Issue by afiebig** [cloudnative-pg/cloudnative-pg.github.io#106]
By default `sidecar.dashboards.enabled` is set to false as stated in [The Grafana Helm Chart Doc](https://github.com/grafana/helm-charts/tree/main/charts/grafana#grafana-helm-chart) 

It has to be enabled in this config in order to Grafana automatically creates the dashboard from the configMap.

https://github.com/cloudnative-pg/cloudnative-pg.github.io/blob/bb91f6fff4b28f06294c088047d356ba7b11dd9e/assets/documentation/1.18/samples/monitoring/kube-stack-config.yaml#L61-L65

It Should look lile:

```yaml
  grafana:
    enabled: true
    # -- the grafana admin password
    adminPassword: prom-operator
    defaultDashboardsEnabled: false
    sidecar:
      dashboards:
        enabled: true
```
